# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: gatewayserver-deployment
serviceName: gatewayserver
appLabel: gatewayserver
appName: gatewayserver

replicaCount: 1

image:
  repository: jahangirzada/gatewayserver
  tag: 1.0.1

containerPort: 8080

service:
  type: LoadBalancer
  port: 8080
  targetPort: 8080

appname_enabled: true
profile_enabled: false
config_enabled: false
eureka_enabled: true
resouceserver_enabled: true
otel_enabled: true
kafka_enabled: false