version: '3'
services:
  config-server:
    build: config-server
    image: config-server
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - my_network
    depends_on:
      - db

  person-service:
    build: ./person
    image: person-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME="person-service"
      - SPRING_CONFIG_IMPORT="configserver:http://config-server:8888"
      - SPRING_PROFILES_ACTIVE=default
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/product
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root

    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - my_network

  work:
    build: ./work
    image: work
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME="work"
      - SPRING_CONFIG_IMPORT="configserver:http://config-server:8888"
      - SPRING_PROFILES_ACTIVE=default
    depends_on:
      config-server:
        condition: service_healthy
    networks:
      - my_network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=product
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    networks:
      - my_network
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  my_network:

volumes:
  postgres_data:
