# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: work-deployment
serviceName: work
appLabel: work
appName: work

replicaCount: 1

image:
  repository: jahangirzada/work-service
  tag: 1.0.1

containerPort: 8081

service:
  type: LoadBalancer
  port: 8081
  targetPort: 8081

appname_enabled: true
profile_enabled: true
config_enabled: true
eureka_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false