spring:
  config:
    import: "optional:configserver:http://localhost:8888/"
  cloud:
    config:
      name: work-service
      profile: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"
