spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/div7625605/microservice-config.git
          username: cahangirzadenurlan043
          password: glpat-M8XcDdtJzVo8F6Qyq6xU
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

