apiVersion: apps/v1
kind: Deployment
metadata:
  name: work-deployment
  labels:
    app: work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: work
  template:
    metadata:
      labels:
        app: work
    spec:
      containers:
        - name: work
          image: jahangirzada/work-service:1.0.1
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_APPLICATION_NAME
              valueFrom:
                configMapKeyRef:
                  name: jahangirzada-configmap
                  key: WORK_APPLICATION_NAME
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: jahangirzada-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: jahangirzada-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: jahangirzada-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: work
spec:
  selector:
    app: work
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
