spring:
  application:
    name: gatewayserver
  cloud:
    kubernetes:
      discovery:
        enabled: true
        all-namespaces: true
    discovery:
      client:
        health-indicator:
          enabled: false
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: "http://localhost:8070/realms/master/protocol/openid-connect/certs"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true

server:
  port: 8080
