spring:
  application:
    name: gatewayserver
  cloud:
    gateway:
      routes:
        - id: person
          uri: lb://person
          predicates:
            - Path=/person/**
        - id: work
          uri: lb://work
          predicates:
            - Path=/work/**
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: "http://localhost:8070/realms/master/protocol/openid-connect/certs"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
  info:
    env:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

server:
  port: 8080
