# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: person-deployment
serviceName: person
appLabel: person
appName: person

replicaCount: 1

image:
  repository: jahangirzada/person-service
  tag: 1.0.2

containerPort: 8080

service:
  type: LoadBalancer
  port: 8085
  targetPort: 8085

appname_enabled: true
postgre_enabled: true
profile_enabled: true
config_enabled: true
discovery_enabled: true
resouceserver_enabled: false
otel_enabled: true
kafka_enabled: false

postgresql:
  enabled: true
  postgresUsername: postgres
  postgresPassword: root
  datasourceURL: jdbc:postgresql://postgresql:5432/product